### ISSUE TITLE
bootStrapper.Initialize()

### ISSUE THREAD

**Issue by forenheith** [SkydivingAngel/Ninject-WebApi-2-and-Mvc5#1]
Hi, Bootstrapper doesn't have method named Initialize

**Comment by SkydivingAngel** [comment]
Hi, take a look into the class "**NinjectWebCommon**":

	public static void Start()
	{
		DynamicModuleUtility.RegisterModule(typeof(OnePerRequestHttpModule));
		DynamicModuleUtility.RegisterModule(typeof(NinjectHttpModule));
	        Bootstrapper.Initialize(CreateKernel);  // <------HERE
	}

**If you right click on initilize and the "go to definition...":
"Bootstrapper.Initialize" is defined in:**

	namespace Ninject.Web.Common
	{
		public class Bootstrapper : IBootstrapper, IHaveKernel
		{
			public Bootstrapper();
			public IKernel Kernel { get; }
			public void Initialize(Func<IKernel> createKernelCallback);
			public void ShutDown();
		}
	}

Cheers

**Comment by forenheith** [comment]
Thanks!

**Comment by SkydivingAngel** [comment]
You're welcome.
Ciao
